/* ============================================================
   BuildIQ — reports.js  (#7: role-scoped report generation)
   Report Type list + Scope selector are both restricted to what the
   signed-in role should be able to generate (see Roles.reportTypesFor).
   Department Managers and Clients get their scope locked to their own
   department / project rather than picking freely.
   ============================================================ */

const ReportsPage = (() => {
  let user;

  function shell() {
    const types = Roles.reportTypesFor(user.role);
    const scopeLocked = Roles.reportScopeLocked(user.role);
    let scopeControl;
    if (user.role === "Client") {
      const myProjects = Roles.visibleProjects(user, MockData.projects);
      scopeControl = `<input class="input" value="${myProjects[0]?.title || "My Project"}" disabled>`;
    } else if (user.role === "Department Manager") {
      scopeControl = `<input class="input" value="${Utils.escapeHtml(user.department)}" disabled>`;
    } else {
      scopeControl = `<select class="input" id="rScope"><option>Entire Organization</option>${MockData.departments.map(d=>`<option>${d.name}</option>`).join("")}</select>`;
    }

    if (!types.length) {
      return `
        <div class="page-header"><div><h1>Reports</h1><div class="page-sub">Report generation is not available for your role</div></div></div>
        ${Components.createEmptyState("fa-file-lines", "No reports available", "Your role does not have report generation access. Ask your manager to generate a report on your behalf.")}`;
    }

    return `
      <div class="page-header"><div><h1>Reports</h1><div class="page-sub">${
        Roles.ORG_WIDE.includes(user.role) ? "Generate AI-powered reports across your organization" :
        user.role === "Department Manager" ? `Generate reports scoped to ${user.department}` :
        user.role === "Auditor" ? "Generate audit & compliance reports" : "View AI-generated reports for your project"
      }</div></div></div>
      <div class="reports-layout">
        <div class="card">
          <div class="section-title"><i class="fa-solid fa-sliders"></i> Report Generator</div>
          <div class="field"><label>Report Type</label><select class="input" id="rType">${types.map(t=>`<option>${t}</option>`).join("")}</select></div>
          <div class="field"><label>Date Range</label><input class="input" id="rDate" placeholder="Select range..."></div>
          <div class="field"><label>Scope</label>${scopeControl}</div>
          <div class="field"><label>Format</label><select class="input" id="rFormat"><option>Screen</option><option>PDF</option><option>Excel</option></select></div>
          <button class="btn btn-primary btn-block" id="genBtn"><i class="fa-solid fa-wand-magic-sparkles"></i> Generate with AI</button>
        </div>
        <div class="card report-preview" id="reportPreview">
          <div class="report-preview-empty">${Components.createEmptyState("fa-file-lines", "No report generated yet", "Configure the options and click Generate with AI.")}</div>
        </div>
      </div>
      <div class="card saved-reports-table">
        <div class="section-title"><i class="fa-solid fa-clock-rotate-left"></i> Saved Reports</div>
        <div class="table-wrap"><table class="data-table" id="savedTable">
          <thead><tr><th>Report Name</th><th>Type</th><th>Date</th><th>Generated By</th><th>Actions</th></tr></thead>
          <tbody></tbody>
        </table></div>
      </div>`;
  }

  const saved = [
    { name: "Q2 Project Progress", type: "Project Progress Summary", date: "2026-06-30", by: "Admin User" },
    { name: "June Complaint Trends", type: "Complaint Analysis", date: "2026-07-01", by: "Tsegaye Worku" },
    { name: "Audit Compliance — H1", type: "Audit & Compliance", date: "2026-07-15", by: "Admin User" },
  ];

  async function init() {
    user = Auth.getUser();
    const content = document.getElementById("pageContent");
    content.innerHTML = shell();
    if (!Roles.reportTypesFor(user.role).length) return;
    if (window.flatpickr) flatpickr("#rDate", { mode: "range", dateFormat: "M j, Y" });
    renderSaved(user);
    document.getElementById("genBtn").addEventListener("click", generate);
  }

  function renderSaved(user) {
    const rows = Roles.ORG_WIDE.includes(user.role) ? saved : saved.filter(r => r.by === user.name);
    document.querySelector("#savedTable tbody").innerHTML = rows.length ? rows.map(r => `
      <tr><td>${r.name}</td><td>${r.type}</td><td>${Utils.formatDate(r.date)}</td><td>${r.by}</td>
      <td><button class="btn btn-ghost btn-sm"><i class="fa-solid fa-download"></i></button></td></tr>`).join("")
      : `<tr><td colspan="5" style="text-align:center; color:var(--text-muted); padding:20px;">No saved reports yet.</td></tr>`;
  }

  async function generate() {
    const type = document.getElementById("rType").value;
    const scopeSelect = document.getElementById("rScope");
    const scope = scopeSelect ? scopeSelect.value : (user.role === "Department Manager" ? user.department : "My Project");
    const preview = document.getElementById("reportPreview");
    preview.innerHTML = `<div style="display:flex; flex-direction:column; align-items:center; justify-content:center; min-height:360px; gap:14px; color:var(--text-secondary);">
      <i class="fa-solid fa-spinner fa-spin" style="font-size:24px; color:var(--accent);"></i><span>Generating report with AI...</span></div>`;
    const result = await API.generateReport({ type, scope });
    preview.innerHTML = `
      <div class="flex items-center justify-between" style="margin-bottom:16px;">
        <div><h3 style="font-size:17px;">${Utils.escapeHtml(type)}</h3><div style="font-size:12.5px;color:var(--text-muted);">Scope: ${Utils.escapeHtml(scope)} · Generated ${Utils.formatDate(result.generated_at)}</div></div>
        <div class="flex gap-8"><button class="btn btn-secondary btn-sm"><i class="fa-solid fa-print"></i> Print</button><button class="btn btn-primary btn-sm"><i class="fa-solid fa-download"></i> Download</button></div>
      </div>
      <div class="divider"></div>
      <div style="font-size:13.5px; line-height:1.8; color:var(--text-secondary);">
        <h4 style="color:var(--text-primary); margin-bottom:8px;">Executive Summary</h4>
        <p style="margin-bottom:16px;">${Utils.escapeHtml(result.content)}</p>
        ${type === "Attendance & Absence Report" ? renderAbsenceRankingTable(result.rankedAbsences) : `
        <h4 style="color:var(--text-primary); margin-bottom:8px;">Key Metrics</h4>
        <div class="grid" style="grid-template-columns:repeat(3,1fr); margin-bottom:16px;">
          <div class="card" style="padding:14px;"><div style="font-size:20px;font-weight:700;">${result.stats?.projects ?? MockData.projects.length}</div><div style="font-size:11.5px;color:var(--text-muted);">Projects</div></div>
          <div class="card" style="padding:14px;"><div style="font-size:20px;font-weight:700;">${result.stats?.complaints ?? MockData.complaints.length}</div><div style="font-size:11.5px;color:var(--text-muted);">Complaints</div></div>
          <div class="card" style="padding:14px;"><div style="font-size:20px;font-weight:700;">${result.stats?.members ?? MockData.members.length}</div><div style="font-size:11.5px;color:var(--text-muted);">Team Members</div></div>
        </div>`}
      </div>`;
    EntityDetail.bindAuto(preview);
    saved.unshift({ name: type, type, date: new Date().toISOString(), by: user.name });
    renderSaved(user);
    Components.createToast("Report generated successfully.", "success");
  }

  function renderAbsenceRankingTable(ranked = []) {
    if (!ranked.length) return `<p style="color:var(--text-muted);">No attendance data available for this scope.</p>`;
    return `
      <h4 style="color:var(--text-primary); margin-bottom:8px;">AI Absence Ranking</h4>
      <div class="table-wrap" style="margin-bottom:8px;"><table class="data-table">
        <thead><tr><th>#</th><th>Person</th><th>Type</th><th>Absence Rate</th><th>AI Risk</th></tr></thead>
        <tbody>${ranked.slice(0,15).map((r,i) => `
          <tr>
            <td>${i+1}</td>
            <td><span class="clickable-entity" data-entity="${r.person_type === 'daily_worker' ? 'daily_worker' : 'member'}" data-id="${r.person_id}" style="cursor:pointer; font-weight:600;">${Utils.escapeHtml(r.person_name)}</span></td>
            <td>${Components.createBadge(r.person_type === "daily_worker" ? "Daily Worker" : "Staff", "gray")}</td>
            <td>${r.absence_rate}%</td>
            <td>${Components.createBadge(r.ai_risk, Utils.priorityBadgeType(r.ai_risk))}</td>
          </tr>`).join("")}</tbody>
      </table></div>`;
  }

  return { init };
})();
