/* ============================================================
   BuildIQ — reports.js  (#7: role-scoped report generation)
   Report Type list + Scope selector are both restricted to what the
   signed-in role should be able to generate (see Roles.reportTypesFor).
   Department Managers and Clients get their scope locked to their own
   department / project rather than picking freely.
   ============================================================ */

const ReportsPage = (() => {
  let user;

  function shell() {
    const types = Roles.reportTypesFor(user.role);
    const scopeLocked = Roles.reportScopeLocked(user.role);
    let scopeControl;
    if (user.role === "Client") {
      const myProjects = Roles.visibleProjects(user, DataStore.projects);
      scopeControl = `<input class="input" value="${myProjects[0]?.title || "My Project"}" disabled>`;
    } else if (user.role === "Department Manager") {
      scopeControl = `<input class="input" value="${Utils.escapeHtml(user.department)}" disabled>`;
    } else {
      scopeControl = Components.createTypedInput({ id: "rScope", value: "Entire Organization", placeholder: "Type a scope...", allowNew: false, options: ["Entire Organization", ...DataStore.departments.map(d => d.name)] });
    }

    if (!types.length) {
      return `
        <div class="page-header"><div><h1>Reports</h1><div class="page-sub">Report generation is not available for your role</div></div></div>
        ${Components.createEmptyState("fa-file-lines", "No reports available", "Your role does not have report generation access. Ask your manager to generate a report on your behalf.")}`;
    }

    return `
      <div class="page-header"><div><h1>Reports</h1><div class="page-sub">${
        Roles.ORG_WIDE.includes(user.role) ? "Generate AI-powered reports across your organization" :
        user.role === "Department Manager" ? `Generate reports scoped to ${user.department}` :
        user.role === "Auditor" ? "Generate audit & compliance reports" : "View AI-generated reports for your project"
      }</div></div></div>
      <div class="reports-layout">
        <div class="card">
          <div class="section-title"><i class="fa-solid fa-sliders"></i> Report Generator</div>
          <div class="field"><label for="rType">Report Type</label>${Components.createTypedInput({ id: "rType", value: types[0] || "", placeholder: "Type a report type...", allowNew: false, options: types })}</div>
          <div class="field"><label>Date Range</label><input class="input" id="rDate" placeholder="Select range..."></div>
          <div class="field"><label>Scope</label>${scopeControl}</div>
          <div class="field"><label for="rFormat">Format</label>${Components.createTypedInput({ id: "rFormat", value: "Screen", placeholder: "Type a format...", allowNew: false, options: ["Screen","PDF","Excel"] })}</div>
          <button class="btn btn-primary btn-block" id="genBtn"><i class="fa-solid fa-wand-magic-sparkles"></i> Generate with AI</button>
        </div>
        <div class="card report-preview" id="reportPreview">
          <div class="report-preview-empty">${Components.createEmptyState("fa-file-lines", "No report generated yet", "Configure the options and click Generate with AI.")}</div>
        </div>
      </div>
      <div class="card saved-reports-table">
        <div class="section-title"><i class="fa-solid fa-clock-rotate-left"></i> Saved Reports</div>
        <div class="table-wrap"><table class="data-table" id="savedTable">
          <thead><tr><th>Report Name</th><th>Type</th><th>Date</th><th>Generated By</th><th>Actions</th></tr></thead>
          <tbody></tbody>
        </table></div>
      </div>`;
  }

  const saved = [
    { name: "Q2 Project Progress", type: "Project Progress Summary", date: "2026-06-30", by: "Admin User" },
    { name: "June Complaint Trends", type: "Complaint Analysis", date: "2026-07-01", by: "Tsegaye Worku" },
    { name: "Audit Compliance — H1", type: "Audit & Compliance", date: "2026-07-15", by: "Admin User" },
  ];

  async function init() {
    // Load real server data before rendering.
    await DataStore.load(["projects","members","departments","complaints"]);
    user = Auth.getUser();
    const content = document.getElementById("pageContent");
    content.innerHTML = shell();
    if (!Roles.reportTypesFor(user.role).length) return;
    if (window.flatpickr) flatpickr("#rDate", { mode: "range", dateFormat: "M j, Y" });
    renderSaved(user);
    document.getElementById("genBtn").addEventListener("click", generate);
  }

  function renderSaved(user) {
    const rows = Roles.ORG_WIDE.includes(user.role) ? saved : saved.filter(r => r.by === user.name);
    document.querySelector("#savedTable tbody").innerHTML = rows.length ? rows.map((r, i) => `
      <tr><td>${Utils.escapeHtml(r.name)}</td><td>${Utils.escapeHtml(r.type)}</td><td>${Utils.formatDate(r.date)}</td><td>${Utils.escapeHtml(r.by)}</td>
      <td><button class="btn btn-ghost btn-sm saved-dl-btn" data-idx="${saved.indexOf(r)}" title="Download" aria-label="Download ${Utils.escapeHtml(r.name)}"><i class="fa-solid fa-download"></i></button></td></tr>`).join("")
      : `<tr><td colspan="5" style="text-align:center; color:var(--text-muted); padding:20px;">No saved reports yet.</td></tr>`;

    Utils.qsa(".saved-dl-btn").forEach(btn => btn.addEventListener("click", () => {
      const rec = saved[Number(btn.dataset.idx)];
      if (!rec) return;
      // Seeded history rows have no generated payload — synthesize a minimal one.
      const result = rec.result || {
        generated_at: rec.date,
        content: `Archived ${rec.type} generated on ${Utils.formatDate(rec.date)} by ${rec.by}. Re-generate the report to see current figures.`,
        stats: null,
      };
      downloadReport(rec.type, rec.scope || "Entire Organization", result);
    }));
  }

  async function generate() {
    const type = document.getElementById("rType").value;
    const scopeSelect = document.getElementById("rScope");
    const scope = scopeSelect ? scopeSelect.value : (user.role === "Department Manager" ? user.department : "My Project");
    const preview = document.getElementById("reportPreview");
    preview.innerHTML = `<div style="display:flex; flex-direction:column; align-items:center; justify-content:center; min-height:360px; gap:14px; color:var(--text-secondary);">
      <i class="fa-solid fa-spinner fa-spin" style="font-size:24px; color:var(--accent);"></i><span>Generating report with AI...</span></div>`;
    const result = await API.generateReport({ type, scope });
    preview.innerHTML = `
      <div class="flex items-center justify-between" style="margin-bottom:16px;">
        <div><h3 style="font-size:17px;">${Utils.escapeHtml(type)}</h3><div style="font-size:12.5px;color:var(--text-muted);">Scope: ${Utils.escapeHtml(scope)} · Generated ${Utils.formatDate(result.generated_at)}</div></div>
        <div class="flex gap-8"><button class="btn btn-secondary btn-sm" id="printReportBtn"><i class="fa-solid fa-print"></i> Print</button><button class="btn btn-primary btn-sm" id="downloadReportBtn"><i class="fa-solid fa-download"></i> Download</button></div>
      </div>
      <div class="divider"></div>
      <div style="font-size:13.5px; line-height:1.8; color:var(--text-secondary);">
        <h4 style="color:var(--text-primary); margin-bottom:8px;">Executive Summary</h4>
        <p style="margin-bottom:16px;">${Utils.escapeHtml(result.content)}</p>
        ${type === "Attendance & Absence Report" ? renderAbsenceRankingTable(result.rankedAbsences) : `
        <h4 style="color:var(--text-primary); margin-bottom:8px;">Key Metrics</h4>
        <div class="grid" style="grid-template-columns:repeat(3,1fr); margin-bottom:16px;">
          <div class="card" style="padding:14px;"><div style="font-size:20px;font-weight:700;">${result.stats?.projects ?? DataStore.projects.length}</div><div style="font-size:11.5px;color:var(--text-muted);">Projects</div></div>
          <div class="card" style="padding:14px;"><div style="font-size:20px;font-weight:700;">${result.stats?.complaints ?? DataStore.complaints.length}</div><div style="font-size:11.5px;color:var(--text-muted);">Complaints</div></div>
          <div class="card" style="padding:14px;"><div style="font-size:20px;font-weight:700;">${result.stats?.members ?? DataStore.members.length}</div><div style="font-size:11.5px;color:var(--text-muted);">Team Members</div></div>
        </div>`}
      </div>`;
    EntityDetail.bindAuto(preview);

    document.getElementById("downloadReportBtn").addEventListener("click", () => downloadReport(type, scope, result));
    document.getElementById("printReportBtn").addEventListener("click", () => printReport(type, scope, result));

    saved.unshift({ name: type, type, date: new Date().toISOString(), by: user.name, result, scope });
    renderSaved(user);
    Components.createToast("Report generated successfully.", "success");
  }

  // ---------------- Real file output ----------------
  function buildReportText(type, scope, result) {
    const lines = [
      "=".repeat(64),
      `BuildIQ — ${type}`,
      "=".repeat(64),
      `Scope:        ${scope}`,
      `Generated at: ${new Date(result.generated_at).toLocaleString()}`,
      `Generated by: ${user.name} (${user.role})`,
      "",
      "EXECUTIVE SUMMARY",
      "-".repeat(64),
      wrapText(result.content, 78),
      "",
    ];

    if (type === "Attendance & Absence Report" && result.rankedAbsences?.length) {
      lines.push("AI ABSENCE RANKING", "-".repeat(64));
      lines.push(pad("#", 5) + pad("Person", 26) + pad("Type", 15) + pad("Absence", 10) + "AI Risk");
      result.rankedAbsences.forEach((r, i) => {
        lines.push(
          pad(String(i + 1), 5) +
          pad(r.person_name, 26) +
          pad(r.person_type === "daily_worker" ? "Daily Worker" : "Staff", 15) +
          pad(`${r.absence_rate}%`, 10) +
          r.ai_risk
        );
      });
    } else if (result.stats) {
      lines.push("KEY METRICS", "-".repeat(64));
      lines.push(`Projects:      ${result.stats.projects}`);
      lines.push(`Complaints:    ${result.stats.complaints}`);
      lines.push(`Team members:  ${result.stats.members}`);
    }

    lines.push("", "-".repeat(64), "Generated by BuildIQ — AI-Powered Construction Management");
    return lines.join("\n");
  }

  function pad(s, n) { s = String(s); return s.length >= n ? s.slice(0, n - 1) + " " : s.padEnd(n); }

  function wrapText(text, width) {
    const words = String(text).split(/\s+/);
    const out = [];
    let line = "";
    words.forEach(w => {
      if ((line + " " + w).trim().length > width) { out.push(line.trim()); line = w; }
      else line += " " + w;
    });
    if (line.trim()) out.push(line.trim());
    return out.join("\n");
  }

  function slugify(s) { return String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }

  function downloadReport(type, scope, result) {
    const text = buildReportText(type, scope, result);
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `buildiq-${slugify(type)}-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    AppEvents.logAudit(user, "EXPORT_DATA", `reports/${slugify(type)}`);
    Components.createToast("Report downloaded.", "success");
  }

  function printReport(type, scope, result) {
    const win = window.open("", "_blank", "width=860,height=900");
    if (!win) { Components.createToast("Pop-up blocked — allow pop-ups to print.", "error"); return; }

    const rankingTable = (type === "Attendance & Absence Report" && result.rankedAbsences?.length) ? `
      <h2>AI Absence Ranking</h2>
      <table>
        <thead><tr><th>#</th><th>Person</th><th>Type</th><th>Absence Rate</th><th>AI Risk</th></tr></thead>
        <tbody>${result.rankedAbsences.map((r, i) => `
          <tr><td>${i + 1}</td><td>${Utils.escapeHtml(r.person_name)}</td>
          <td>${r.person_type === "daily_worker" ? "Daily Worker" : "Staff"}</td>
          <td>${r.absence_rate}%</td><td>${r.ai_risk}</td></tr>`).join("")}</tbody>
      </table>` : result.stats ? `
      <h2>Key Metrics</h2>
      <table>
        <tbody>
          <tr><th>Projects</th><td>${result.stats.projects}</td></tr>
          <tr><th>Complaints</th><td>${result.stats.complaints}</td></tr>
          <tr><th>Team members</th><td>${result.stats.members}</td></tr>
        </tbody>
      </table>` : "";

    win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${Utils.escapeHtml(type)} — BuildIQ</title>
      <style>
        *{box-sizing:border-box}
        body{font-family:-apple-system,Segoe UI,Inter,Helvetica,Arial,sans-serif;color:#111;margin:40px;line-height:1.6}
        h1{font-size:22px;margin:0 0 4px}
        .meta{color:#666;font-size:12.5px;margin-bottom:20px;border-bottom:2px solid #F97316;padding-bottom:14px}
        h2{font-size:15px;margin:24px 0 8px;color:#111}
        p{font-size:13.5px}
        table{width:100%;border-collapse:collapse;margin-top:8px;font-size:12.5px}
        th,td{border:1px solid #ddd;padding:7px 9px;text-align:left}
        th{background:#f5f5f5;font-weight:600}
        footer{margin-top:36px;padding-top:12px;border-top:1px solid #ddd;color:#888;font-size:11px}
        @media print{body{margin:16mm}}
      </style></head><body>
        <h1>${Utils.escapeHtml(type)}</h1>
        <div class="meta">
          Scope: <b>${Utils.escapeHtml(scope)}</b><br>
          Generated ${new Date(result.generated_at).toLocaleString()} by ${Utils.escapeHtml(user.name)} (${Utils.escapeHtml(user.role)})
        </div>
        <h2>Executive Summary</h2>
        <p>${Utils.escapeHtml(result.content)}</p>
        ${rankingTable}
        <footer>Generated by BuildIQ — AI-Powered Construction Organization Management System</footer>
      </body></html>`);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 300);
    AppEvents.logAudit(user, "EXPORT_DATA", `reports/${slugify(type)}/print`);
  }

  function renderAbsenceRankingTable(ranked = []) {
    if (!ranked.length) return `<p style="color:var(--text-muted);">No attendance data available for this scope.</p>`;
    return `
      <h4 style="color:var(--text-primary); margin-bottom:8px;">AI Absence Ranking</h4>
      <div class="table-wrap" style="margin-bottom:8px;"><table class="data-table">
        <thead><tr><th>#</th><th>Person</th><th>Type</th><th>Absence Rate</th><th>AI Risk</th></tr></thead>
        <tbody>${ranked.slice(0,15).map((r,i) => `
          <tr>
            <td>${i+1}</td>
            <td><span class="clickable-entity" data-entity="${r.person_type === 'daily_worker' ? 'daily_worker' : 'member'}" data-id="${r.person_id}" style="cursor:pointer; font-weight:600;">${Utils.escapeHtml(r.person_name)}</span></td>
            <td>${Components.createBadge(r.person_type === "daily_worker" ? "Daily Worker" : "Staff", "gray")}</td>
            <td>${r.absence_rate}%</td>
            <td>${Components.createBadge(r.ai_risk, Utils.priorityBadgeType(r.ai_risk))}</td>
          </tr>`).join("")}</tbody>
      </table></div>`;
  }

  return { init };
})();

// Published for the single-page shell: a top-level `const` creates a
// script-scope binding, NOT a window property, so SPA's window[name]
// lookup would otherwise find nothing.
if (typeof window !== "undefined") window.ReportsPage = ReportsPage;
