/* ============================================================
   BuildIQ — reports.js  (A.12)
   ============================================================ */

const ReportsPage = (() => {
  function shell() {
    return `
      <div class="page-header"><div><h1>Reports</h1><div class="page-sub">Generate AI-powered reports across your organization</div></div></div>
      <div class="reports-layout">
        <div class="card">
          <div class="section-title"><i class="fa-solid fa-sliders"></i> Report Generator</div>
          <div class="field"><label>Report Type</label><select class="input" id="rType">
            <option>Project Progress Summary</option><option>Complaint Analysis</option><option>Audit & Compliance</option><option>Team Performance</option><option>Financial Overview</option>
          </select></div>
          <div class="field"><label>Date Range</label><input class="input" id="rDate" placeholder="Select range..."></div>
          <div class="field"><label>Scope</label><select class="input" id="rScope"><option>Entire Organization</option>${MockData.departments.map(d=>`<option>${d.name}</option>`).join("")}</select></div>
          <div class="field"><label>Format</label><select class="input" id="rFormat"><option>Screen</option><option>PDF</option><option>Excel</option></select></div>
          <button class="btn btn-primary btn-block" id="genBtn"><i class="fa-solid fa-wand-magic-sparkles"></i> Generate with AI</button>
        </div>
        <div class="card report-preview" id="reportPreview">
          <div class="report-preview-empty">${Components.createEmptyState("fa-file-lines", "No report generated yet", "Configure the options and click Generate with AI.")}</div>
        </div>
      </div>
      <div class="card saved-reports-table">
        <div class="section-title"><i class="fa-solid fa-clock-rotate-left"></i> Saved Reports</div>
        <div class="table-wrap"><table class="data-table" id="savedTable">
          <thead><tr><th>Report Name</th><th>Type</th><th>Date</th><th>Generated By</th><th>Actions</th></tr></thead>
          <tbody></tbody>
        </table></div>
      </div>`;
  }

  const saved = [
    { name: "Q2 Project Progress", type: "Project Progress Summary", date: "2026-06-30", by: "Admin User" },
    { name: "June Complaint Trends", type: "Complaint Analysis", date: "2026-07-01", by: "Meron Tadesse" },
    { name: "Audit Compliance — H1", type: "Audit & Compliance", date: "2026-07-15", by: "Admin User" },
  ];

  async function init() {
    const content = document.getElementById("pageContent");
    content.innerHTML = shell();
    if (window.flatpickr) flatpickr("#rDate", { mode: "range", dateFormat: "M j, Y" });
    renderSaved();
    document.getElementById("genBtn").addEventListener("click", generate);
  }

  function renderSaved() {
    document.querySelector("#savedTable tbody").innerHTML = saved.map(r => `
      <tr><td>${r.name}</td><td>${r.type}</td><td>${Utils.formatDate(r.date)}</td><td>${r.by}</td>
      <td><button class="btn btn-ghost btn-sm"><i class="fa-solid fa-download"></i></button></td></tr>`).join("");
  }

  async function generate() {
    const type = document.getElementById("rType").value;
    const scope = document.getElementById("rScope").value;
    const preview = document.getElementById("reportPreview");
    preview.innerHTML = `<div style="display:flex; flex-direction:column; align-items:center; justify-content:center; min-height:360px; gap:14px; color:var(--text-secondary);">
      <i class="fa-solid fa-spinner fa-spin" style="font-size:24px; color:var(--accent);"></i><span>Generating report with AI...</span></div>`;
    const result = await API.generateReport({ type, scope });
    preview.innerHTML = `
      <div class="flex items-center justify-between" style="margin-bottom:16px;">
        <div><h3 style="font-size:17px;">${Utils.escapeHtml(type)}</h3><div style="font-size:12.5px;color:var(--text-muted);">Scope: ${Utils.escapeHtml(scope)} · Generated ${Utils.formatDate(result.generated_at)}</div></div>
        <div class="flex gap-8"><button class="btn btn-secondary btn-sm"><i class="fa-solid fa-print"></i> Print</button><button class="btn btn-primary btn-sm"><i class="fa-solid fa-download"></i> Download</button></div>
      </div>
      <div class="divider"></div>
      <div style="font-size:13.5px; line-height:1.8; color:var(--text-secondary);">
        <h4 style="color:var(--text-primary); margin-bottom:8px;">Executive Summary</h4>
        <p style="margin-bottom:16px;">${Utils.escapeHtml(result.content)}</p>
        <h4 style="color:var(--text-primary); margin-bottom:8px;">Key Metrics</h4>
        <div class="grid" style="grid-template-columns:repeat(3,1fr); margin-bottom:16px;">
          <div class="card" style="padding:14px;"><div style="font-size:20px;font-weight:700;">${MockData.projects.length}</div><div style="font-size:11.5px;color:var(--text-muted);">Total Projects</div></div>
          <div class="card" style="padding:14px;"><div style="font-size:20px;font-weight:700;">${MockData.complaints.length}</div><div style="font-size:11.5px;color:var(--text-muted);">Total Complaints</div></div>
          <div class="card" style="padding:14px;"><div style="font-size:20px;font-weight:700;">${MockData.members.length}</div><div style="font-size:11.5px;color:var(--text-muted);">Team Members</div></div>
        </div>
      </div>`;
    saved.unshift({ name: type, type, date: new Date().toISOString(), by: Auth.getUser().name });
    renderSaved();
    Components.createToast("Report generated successfully.", "success");
  }

  return { init };
})();
