-- ============================================================================
-- BuildIQ — seed.sql
-- Minimal reference data: the nine departments.
--
-- The full demo dataset (46 users, 15 projects, attendance history, complaints,
-- audit logs) is generated by app/seed.py on first boot, because it needs
-- bcrypt password hashing and the AI classifier — neither of which belongs in
-- SQL. Set SEED_ON_STARTUP=true and the API handles it.
--
-- This file exists for the case where you want a clean production database
-- with the org structure in place but no demo accounts:
--
--   SEED_ON_STARTUP=false
--   psql "$DATABASE_URL" -f supabase/seed.sql
--
-- Idempotent: re-running updates existing rows rather than duplicating them.
-- ============================================================================

begin;

insert into public.departments (id, name, head, description, scope, budget) values
    ('dep_1', 'Site Operations', 'Unassigned',
     'Runs day-to-day construction activity across all active sites.',
     '["Site scheduling & crew coordination","Equipment allocation","Daily progress tracking","On-site issue escalation"]'::jsonb,
     2400000),

    ('dep_2', 'Engineering & Design', 'Unassigned',
     'Owns structural, architectural and MEP design across the portfolio.',
     '["Structural & architectural drawings","BIM modeling","Design change control","Technical feasibility review"]'::jsonb,
     1800000),

    ('dep_3', 'Finance & Budget', 'Unassigned',
     'Manages project budgets, supplier payments and financial reporting.',
     '["Budget planning & tracking","Invoice & payment processing","Cost variance analysis","Financial reporting"]'::jsonb,
     900000),

    ('dep_4', 'Health & Safety', 'Unassigned',
     'Enforces safety compliance on every site and investigates incidents.',
     '["Site safety audits","PPE compliance","Incident investigation","Safety training"]'::jsonb,
     520000),

    ('dep_5', 'Human Resources', 'Unassigned',
     'Handles hiring, onboarding and workforce administration.',
     '["Recruitment & onboarding","Payroll administration","Employee relations","Training & development"]'::jsonb,
     380000),

    ('dep_6', 'Quality Control', 'Unassigned',
     'Inspects work quality against specification and manages material testing.',
     '["Material testing","Work quality inspection","Non-conformance tracking","Standards compliance"]'::jsonb,
     640000),

    ('dep_7', 'Procurement & Supply', 'Unassigned',
     'Sources materials and manages supplier relationships and deliveries.',
     '["Supplier sourcing & contracts","Purchase order management","Delivery scheduling","Inventory tracking"]'::jsonb,
     1500000),

    ('dep_8', 'Client Relations', 'Unassigned',
     'Primary liaison with clients, managing communication and expectations.',
     '["Client communication","Contract liaison","Satisfaction tracking","Onboarding new clients"]'::jsonb,
     300000),

    -- This department has exclusive authority to take the daily register.
    ('dep_9', 'Workforce & Attendance', 'Unassigned',
     'Supervises daily workforce presence across all sites, for permanent staff and daily workers alike.',
     '["Daily attendance supervision","Organization worker attendance","Daily/casual worker attendance","Absence pattern monitoring","Workforce headcount reporting"]'::jsonb,
     260000)

on conflict (id) do update set
    name        = excluded.name,
    description = excluded.description,
    scope       = excluded.scope,
    budget      = excluded.budget;

commit;
